Create table NOIDUNGPNKSHOW(
	IDNDPNK INT primary key identity,
	SOLUONG FLOAT(10),
	SLC FLOAT(10),
	DONGIA FLOAT(20),
	DONVITINH NVARCHAR(255),
	SOLO NVARCHAR(255),
	NGAYSX DATE,
	HANSD DATE,
	IDPNK INT,
	IDVL INT,
	CONSTRAINT FK_NDPNKSHOWIDPNK FOREIGN KEY (IDPNK)
    REFERENCES PHIEUNHAPKHO(IDPNK),
	CONSTRAINT FK_NDPNKSHOWIDVL FOREIGN KEY (IDVL)
    REFERENCES VATLIEU(IDVL)
)
--reset identity
DBCC CHECKIDENT ('[NOIDUNGPNKSHOW]', RESEED,0)
DBCC CHECKIDENT ('[NOIDUNGPNK]', RESEED,0)
DBCC CHECKIDENT ('[NOIDUNGPBH]', RESEED,0)
DBCC CHECKIDENT ('[NOIDUNGTRANONCC]', RESEED,0)
DBCC CHECKIDENT ('[NOIDUNGTRANOKH]', RESEED,0)